allowBuilds:
  "@swc/core": false
  cbor-extract: false
  esbuild: false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@better-auth/core@1.7.4"
  - "@better-auth/drizzle-adapter@1.7.4"
  - "@better-auth/kysely-adapter@1.7.4"
  - "@better-auth/memory-adapter@1.7.4"
  - "@better-auth/mongo-adapter@1.7.4"
  - "@better-auth/prisma-adapter@1.7.4"
  - "@better-auth/telemetry@1.7.4"
  - better-auth@1.7.4
  - "@ai-sdk/gateway@4.0.81"
  - "@ai-sdk/react@4.0.103"
  - ai@7.0.100
